"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\CEH_PAHCODE.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\CEH_VXREC.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\CEHMRI_SRS_Recode.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\COREPD_COREPD_MERGE_1.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\HWAC2_SPSS_to_SAS.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\KOLLER_SPSS_to_SAS.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\MIND_SPSS_to_SAS.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\MIND_Merge_All.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\NACCUDS_nacc_uds_1.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\NACCUDS_nacc.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\NACCUDS_followup.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\NICU_SPSS_to_SAS.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\NICU_MMM_FNI_Raw_R4.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\ORIGINS_SPSS_to_SAS.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\PREDICT2_MING2.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\PREDICT3_new_merge.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\RAINE_RAINE_SAS.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\SURVEY_MULTALL.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\SURVEY_ONEALL.spj -production
