"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\PAHCODE.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\VXREC.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\SRS_Recode.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\COREPD_MERGE_1.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\SPSS_to_SAS.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\SPSS_to_SAS.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\SPSS_to_SAS.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\Merge_All.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\nacc_uds_1.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\nacc.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\followup.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\SPSS_to_SAS.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\MMM_FNI_Raw_R4.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\SPSS_to_SAS.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\MING2.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\new_merge.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\RAINE_SAS.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\MULTALL.spj -production
"\\192.168.53.236\C$\Program Files\IBM\SPSS\Statistics\23\stats.exe" \\Dccmaincsfs\Data1\DCC\BackupRoutine\Batch\SPSS\ONEALL.spj -production
